RydHQ_Debug = true; RydHQB_Debug = true;
RydHQ_DebugII = true; RydHQB_DebugII = true;
RydHQ_SubAll = false; RydHQB_SubAll = false;
RydHQ_SubSynchro = true; RydHQB_SubSynchro = true;
RydHQ_Surr = true; RydHQB_Surr = true;
RydHQ_NoRec = 10000; RydHQB_NoRec = 10000;
RydHQ_RapidCapt = 10000; RydHQB_RapidCapt = 10000;
//RydHQ_PathFinding = 100;
RydHQ_Rush = true;
RydBBa_HQs = [leaderHQ];
RydBBb_HQs = [leaderHQB];
RydBB_Active = true;
RydBB_Debug = true;
//RydBBa_Str = [];
//RydBBb_Str = [];
//RydBB_CustomObjOnly = false;
//RydBB_BBOnMap = false;
